name: Test
on: [push]
jobs:
  demo:
    name: Test Job
    runs-on: ubuntu-latest
    outputs:
      baseUrl: ${{ secrets.TEST_URL }}
    steps:
      - run: echo "The URL is ${{ secrets.TEST_URL }}"
